version: '3.8'
services:
  finetude:
    container_name: fin_etude_mel
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 1000:1000
    depends_on:
      - db

  db:
    container_name: mysql
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 3306:3306
    volumes:
      - /./dbdata/var/lib/mysql
   
    


    

  