# Generated by Django 3.1.2 on 2021-03-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='image',
            field=models.ImageField(max_length=255, upload_to='Images/'),
        ),
    ]
