# Generated by Django 3.1.2 on 2021-03-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0002_auto_20210308_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='image',
            field=models.ImageField(default='thumb-1920-1073527.png', upload_to='Images/'),
        ),
    ]
